language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt
script:
  - pylama
  - pytest -v --cov=ipam.client
after_success: coveralls
